### ISSUE TITLE
Hungarian grammar fails in AdaGram

### ISSUE THREAD

**Issue by antaranin** [antaranin/ProgramSynthNLP#2]
Traceback (most recent call last):
  File "/Users/Arin/PycharmProjects/MasterThesis/runner.py", line 479, in make_adagrammar_for_languages
    run_adagram(language, split_type, PredType.AdaGramBoth)
  File "/Users/Arin/PycharmProjects/MasterThesis/runner.py", line 364, in run_adagram
    adagram.main(args)
  File "/Users/Arin/PycharmProjects/MasterThesis/PyAdaGram/launch_train.py", line 359, in main
    clock_e_step, clock_m_step = adagram_inferencer.learning(train_doc_set, number_of_processes)
  File "/Users/Arin/PycharmProjects/MasterThesis/PyAdaGram/hybrid.py", line 2702, in learning
    self._number_of_samples)
  File "/Users/Arin/PycharmProjects/MasterThesis/PyAdaGram/hybrid.py", line 845, in e_step
    root_node = self.compute_inside_probabilities(E_log_stick_weights, E_log_theta, parsed_string)
  File "/Users/Arin/PycharmProjects/MasterThesis/PyAdaGram/hybrid.py", line 749, in compute_inside_probabilities
    return root_and_position_to_node[self._start_symbol][(0, sequence_length)]
KeyError: (0, 22)

**Comment by antaranin** [comment]
I am reasonably certain that this is due to grammar provided not being exactly correct and AdaGram ending up in a situation when it cannot parse correctly the data.

**Comment by antaranin** [comment]
Fixed. The issue was uppercase letters in some of the training examples. 
Lowercased all of them and now the problem is gone.
